### ISSUE TITLE
Reported state when no alert

### ISSUE THREAD

**Issue by jazzyisj** [custom-components/sensor.weatheralerts#15]
When there is no active alert sensor.weatheralerts state is reported as 'unknown'.  Because of this I cannot test to see if the sensor is currently connected and active which I would like to do so I receive a notification the component has not connected for some reason.

Would it be possible to have the sensor report "None" when there are no active alerts instead of "unknown"?  Seems like it would be a more intuitive value to report on the front end also.

![image](https://user-images.githubusercontent.com/44064559/55676718-039ece80-58a8-11e9-9fec-35fcd98bcb68.png)

**Comment by ludeeus** [comment]
It does report `None` it is the frontend that "translate" that to "unknown"

**Comment by jazzyisj** [comment]
Thank you for your reply, I can tell by your prolific activity on here you are a busy fellow.

I must be misunderstanding something because for example the sensor.work_holiday sensor visible in the image in my first comment actually reports "None" for a state - in the front end.  I can test for "None" to see if there is a holiday, or test for "unknown" to see if the sensor state actually exists.

So with the weatheralerts sensor, how could one differentiate between no active alert and the sensor not existing and/or not being connected?

**Weatheralerts Sensor connected but no active alert:**
![image](https://user-images.githubusercontent.com/44064559/55684696-43070280-591c-11e9-969d-6da4448e8a79.png)

** Weatheralerts Sensor not instantiated/connected**
![image](https://user-images.githubusercontent.com/44064559/55684793-59618e00-591d-11e9-96d2-5f10ba017613.png)

**Comment by ludeeus** [comment]
Your work_holyday sensor must be doing something wierdness, that is not the expected behavior, what you see from this sensor is, a sensor have two "modes" 
- No data/unknown state resulting in `None`
- Data, resulting in the data being displayed

Difference the tests if it exist or has no data does not make sense, to the user the result is the same, the sensor does not contain data in both scenarios
