### ISSUE TITLE
ERROR (MainThread) [custom_components.weatheralerts.sensor] list index out of range

### ISSUE THREAD

**Issue by jazzyisj** [custom-components/sensor.weatheralerts#16]
**Version of the cusom_component**
Weatheralerts Version= "0.1.1"
HASSIO Version = "0.91.0"

**Describe the bug**
When there is **no active alert** the following error appears during startup and then repeats in the every 30 seconds.  When there is an active alert the sensor behaves has expected with no errors in the log.

`ERROR (MainThread) [custom_components.weatheralerts.sensor] list index out of range`

**log**
Note: I have set the log for weather alerts to debug but do not get any more detail on this error.
![weather log](https://user-images.githubusercontent.com/44064559/55684531-d4c14080-5919-11e9-9861-2a64b052c221.JPG)
Add your logs here.
```

**Comment by kflinderman** [comment]
I have been getting this same issue in 0.96.5.

List index out of range.

My config is setup like it should:
```
platform: weatheralerts
sameid: '037063'
```
I haven't been able to get it working for that sameid though. I was having troubles yesterday and just decided to go to the sameid from the docs. I was getting `not well formed (invalid token)` but woke up this morning to it working so I changed id and here I am.

HACS says I'm on version 9acd01b.

**Comment by niemyjski** [comment]
I'm getting this error as well but I'm using the id: `055009`
